apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-thanos-store-0-pv
  namespace: thanos
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus-storage-class  # Changed to match PVC
  hostPath:
    path: /mnt/data
