apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-thanos-store-0
  namespace: thanos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: prometheus-storage-class  # Ensure this matches PV
