apiVersion: v1
kind: Secret
metadata:
  name: thanos-storage
  namespace: thanos
  annotations:
    "helm.sh/hook": post-install
type: Opaque
data:
  thanos.yaml: {{ .Files.Get "files/thanos-storage-config.yaml" | b64enc }}
